pipeline {
  agent any

  environment {
    IMAGE_NAME = "sagarpatil98/demoyoutubeautomation"
    TAG = "${BUILD_NUMBER}"
  }

  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $IMAGE_NAME:$TAG .'
      }
    }

    stage('Push Image') {
      steps {
        sh 'docker push $IMAGE_NAME:$TAG'
      }
    }
  }
}

